name: Generate Vaev's benchmarks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_benchmarks:
    name: Vaev
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Process data.
        run: |
          pip install psutils
          python prepareBenchmarks.py
          python ./samples/benchs/benchmark.py
