name: WPT compliance check

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  wpt_job:
    runs-on: python:3.11-slim-bookworm
    name: Run WPT compliance check
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh