name: WPT compliance check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_wpt:
    name: Vaev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        current-chunk: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
        total-chunks: [ 8 ]
    timeout-minutes: 180
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: prepare environment.
        run: | 
          python prepare.py
          PATH=$PATH:$HOME/.local/opt/paper-muncher/bin 
          cd wpt && \
          ./wpt run paper_muncher --webdriver-binary paper_muncher_webdriver \
          --test-type=reftest --log-wptreport ./result_${{ matrix.current-chunk }}.json \
          --this-chunk=${{ matrix.current-chunk }} \
          --total-chunks=${{ matrix.total-chunks }} \
          --no-fail-on-unexpected \
          --include-file ../wpt-whitelist
          ls

      - name: Publish results
        uses: actions/upload-artifact@v4.1.0
        with:
          name: wpt-log-${{ matrix.current-chunk }}
          path: |
            ./wpt/wpt_report_*.json
          if-no-files-found: "error"

  collect_results:
    needs: run_wpt
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: process WPT results
        run: python processResults.py
